SELECT COUNT(mid) FROM casts;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(mid) FROM casts;
UPDATE genre SET genre = 'News' WHERE genre = 'News';
SELECT COUNT(name) FROM movie;
SELECT COUNT(lname) FROM directors;
SELECT COUNT(name) FROM movie;
SELECT COUNT(year) FROM movie;
SELECT COUNT(fname) FROM directors;
SELECT COUNT(lname) FROM actor;
SELECT COUNT(id) FROM actor;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(name) FROM movie;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(id) FROM actor;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(id) FROM movie;
SELECT COUNT(id) FROM movie;
SELECT COUNT(lname) FROM directors;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(did) FROM movie_directors;
UPDATE movie_directors SET mid = '916248' WHERE mid = '916248';
SELECT COUNT(fname) FROM directors;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(id) FROM movie;
SELECT COUNT(mid) FROM movie_directors;
UPDATE genre SET genre = 'Fantasy' WHERE genre = 'Fantasy';
SELECT COUNT(pid) FROM casts;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(id) FROM movie;
SELECT COUNT(id) FROM movie;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(lname) FROM actor;
SELECT COUNT(fname) FROM directors;
UPDATE directors SET fname = ' Pawel' WHERE fname = ' Pawel';
SELECT COUNT(fname) FROM actor;
SELECT COUNT(year) FROM movie;
SELECT COUNT(id) FROM directors;
UPDATE movie SET year = '1979' WHERE year = '1979';
SELECT COUNT(fname) FROM actor;
SELECT COUNT(name) FROM movie;
UPDATE actor SET id = '1153043' WHERE id = '1153043';
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(mid) FROM casts;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(lname) FROM actor;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(mid) FROM casts;
SELECT COUNT(year) FROM movie;
UPDATE actor SET id = '1830921' WHERE id = '1830921';
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(mid) FROM casts;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(fname) FROM directors;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(mid) FROM casts;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(name) FROM movie;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(id) FROM movie;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(name) FROM movie;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(lname) FROM actor;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(id) FROM actor;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(fname) FROM actor;
UPDATE movie SET year = '1969' WHERE year = '1969';
SELECT COUNT(pid) FROM casts;
SELECT COUNT(genre) FROM genre;
UPDATE movie SET name = 'Mikey and Nicky' WHERE name = 'Mikey and Nicky';
SELECT COUNT(pid) FROM casts;
UPDATE genre SET genre = 'Documentary' WHERE genre = 'Documentary';
SELECT COUNT(lname) FROM actor;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(id) FROM movie;
SELECT COUNT(name) FROM movie;
SELECT COUNT(name) FROM movie;
SELECT COUNT(year) FROM movie;
SELECT COUNT(fname) FROM actor;
