UPDATE directors SET id = '157157' WHERE id = '157157';
SELECT COUNT(mid) FROM genre;
SELECT COUNT(id) FROM actor;
UPDATE movie SET year = '2009' WHERE year = '2009';
UPDATE directors SET id = '52640' WHERE id = '52640';
SELECT COUNT(genre) FROM genre;
UPDATE genre SET genre = 'Drama' WHERE genre = 'Drama';
SELECT COUNT(id) FROM actor;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(fname) FROM actor;
UPDATE directors SET id = '99798' WHERE id = '99798';
UPDATE directors SET id = '8707' WHERE id = '8707';
UPDATE directors SET lname = 'Nielsen' WHERE lname = 'Nielsen';
SELECT COUNT(mid) FROM casts;
SELECT COUNT(id) FROM actor;
UPDATE genre SET genre = 'Drama' WHERE genre = 'Drama';
SELECT COUNT(genre) FROM genre;
SELECT COUNT(lname) FROM directors;
UPDATE directors SET lname = 'Del Prete' WHERE lname = 'Del Prete';
UPDATE movie_directors SET did = '179043' WHERE did = '179043';
SELECT COUNT(mid) FROM genre;
UPDATE movie_directors SET mid = '603506' WHERE mid = '603506';
UPDATE genre SET mid = '1001638' WHERE mid = '1001638';
UPDATE directors SET lname = 'Portal' WHERE lname = 'Portal';
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(id) FROM actor;
UPDATE movie SET year = '1963' WHERE year = '1963';
UPDATE directors SET lname = 'Kraus' WHERE lname = 'Kraus';
UPDATE movie SET year = '1912' WHERE year = '1912';
UPDATE genre SET mid = '151059' WHERE mid = '151059';
UPDATE movie_directors SET mid = '232412' WHERE mid = '232412';
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(lname) FROM actor;
SELECT COUNT(id) FROM actor;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(year) FROM movie;
SELECT COUNT(name) FROM movie;
SELECT COUNT(name) FROM movie;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(mid) FROM genre;
UPDATE movie SET id = '78922' WHERE id = '78922';
UPDATE actor SET lname = 'Holden' WHERE lname = 'Holden';
UPDATE genre SET mid = '829345' WHERE mid = '829345';
UPDATE movie SET name = 'Tvali patiosani' WHERE name = 'Tvali patiosani';
UPDATE movie SET id = '862010' WHERE id = '862010';
UPDATE movie SET year = '1924' WHERE year = '1924';
SELECT COUNT(genre) FROM genre;
UPDATE genre SET genre = 'Comedy' WHERE genre = 'Comedy';
UPDATE genre SET mid = '382279' WHERE mid = '382279';
SELECT COUNT(mid) FROM movie_directors;
UPDATE casts SET mid = '1430795' WHERE mid = '1430795';
UPDATE movie SET name = '(#2.12)' WHERE name = '(#2.12)';
UPDATE casts SET mid = '68716' WHERE mid = '68716';
UPDATE directors SET fname = ' Sam' WHERE fname = ' Sam';
SELECT COUNT(did) FROM movie_directors;
UPDATE movie_directors SET did = '189746' WHERE did = '189746';
SELECT COUNT(genre) FROM genre;
SELECT COUNT(mid) FROM genre;
UPDATE actor SET fname = 'Dave' WHERE fname = 'Dave';
UPDATE actor SET lname = 'Kireev' WHERE lname = 'Kireev';
UPDATE actor SET lname = 'Arthur' WHERE lname = 'Arthur';
UPDATE movie_directors SET did = '130692' WHERE did = '130692';
SELECT COUNT(genre) FROM genre;
SELECT COUNT(id) FROM actor;
SELECT COUNT(id) FROM movie;
UPDATE actor SET id = '1667308' WHERE id = '1667308';
SELECT COUNT(mid) FROM casts;
UPDATE genre SET mid = '368522' WHERE mid = '368522';
UPDATE directors SET id = '123052' WHERE id = '123052';
SELECT COUNT(pid) FROM casts;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(lname) FROM directors;
UPDATE casts SET pid = '1652783' WHERE pid = '1652783';
SELECT COUNT(mid) FROM genre;
UPDATE casts SET pid = '1188655' WHERE pid = '1188655';
UPDATE movie_directors SET mid = '1167042' WHERE mid = '1167042';
SELECT COUNT(mid) FROM casts;
UPDATE casts SET pid = '912763' WHERE pid = '912763';
SELECT COUNT(id) FROM directors;
SELECT COUNT(id) FROM directors;
SELECT COUNT(id) FROM actor;
UPDATE directors SET fname = ' Christopher' WHERE fname = ' Christopher';
UPDATE actor SET fname = 'Christopher' WHERE fname = 'Christopher';
UPDATE movie SET name = '(2004-05-23)' WHERE name = '(2004-05-23)';
SELECT COUNT(mid) FROM casts;
UPDATE directors SET lname = 'Moran' WHERE lname = 'Moran';
SELECT COUNT(name) FROM movie;
UPDATE movie_directors SET did = '129564' WHERE did = '129564';
SELECT COUNT(id) FROM movie;
SELECT COUNT(fname) FROM actor;
UPDATE movie_directors SET did = '173356' WHERE did = '173356';
UPDATE genre SET mid = '289423' WHERE mid = '289423';
SELECT COUNT(lname) FROM directors;
SELECT COUNT(mid) FROM movie_directors;
UPDATE movie_directors SET did = '81905' WHERE did = '81905';
SELECT COUNT(mid) FROM genre;
SELECT COUNT(genre) FROM genre;
