SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(name) FROM movie;
UPDATE casts SET mid = '225767' WHERE mid = '225767';
UPDATE genre SET genre = 'Drama' WHERE genre = 'Drama';
SELECT COUNT(name) FROM movie;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(lname) FROM directors;
SELECT COUNT(mid) FROM casts;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(id) FROM directors;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(fname) FROM directors;
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(year) FROM movie;
SELECT COUNT(lname) FROM directors;
UPDATE movie_directors SET did = '49207' WHERE did = '49207';
UPDATE casts SET pid = '1486767' WHERE pid = '1486767';
SELECT COUNT(mid) FROM casts;
SELECT COUNT(lname) FROM directors;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(fname) FROM actor;
UPDATE movie SET year = '1972' WHERE year = '1972';
UPDATE directors SET lname = 'Schreiber' WHERE lname = 'Schreiber';
SELECT COUNT(did) FROM movie_directors;
SELECT COUNT(lname) FROM directors;
SELECT COUNT(fname) FROM directors;
UPDATE movie_directors SET did = '174959' WHERE did = '174959';
SELECT COUNT(name) FROM movie;
SELECT COUNT(id) FROM directors;
SELECT COUNT(genre) FROM genre;
UPDATE actor SET fname = 'Carleton' WHERE fname = 'Carleton';
SELECT COUNT(mid) FROM casts;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(fname) FROM directors;
SELECT COUNT(id) FROM movie;
SELECT COUNT(id) FROM directors;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(mid) FROM genre;
SELECT COUNT(genre) FROM genre;
SELECT COUNT(pid) FROM casts;
UPDATE directors SET fname = ' Lilli' WHERE fname = ' Lilli';
SELECT COUNT(mid) FROM genre;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(id) FROM directors;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(pid) FROM casts;
UPDATE directors SET id = '16034' WHERE id = '16034';
SELECT COUNT(lname) FROM directors;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(did) FROM movie_directors;
UPDATE movie_directors SET mid = '1432334' WHERE mid = '1432334';
SELECT COUNT(name) FROM movie;
SELECT COUNT(genre) FROM genre;
UPDATE genre SET mid = '113594' WHERE mid = '113594';
SELECT COUNT(fname) FROM actor;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(lname) FROM actor;
SELECT COUNT(mid) FROM casts;
SELECT COUNT(mid) FROM genre;
UPDATE movie_directors SET mid = '355216' WHERE mid = '355216';
SELECT COUNT(name) FROM movie;
SELECT COUNT(genre) FROM genre;
UPDATE casts SET mid = '363216' WHERE mid = '363216';
SELECT COUNT(id) FROM directors;
UPDATE movie_directors SET mid = '1338498' WHERE mid = '1338498';
SELECT COUNT(did) FROM movie_directors;
UPDATE genre SET mid = '206037' WHERE mid = '206037';
UPDATE movie SET name = 'Laurie Goes on a Diet' WHERE name = 'Laurie Goes on a Diet';
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(id) FROM directors;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(id) FROM directors;
UPDATE movie SET year = '2007' WHERE year = '2007';
UPDATE movie_directors SET mid = '343610' WHERE mid = '343610';
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(lname) FROM directors;
UPDATE casts SET mid = '1577562' WHERE mid = '1577562';
UPDATE directors SET id = '92224' WHERE id = '92224';
SELECT COUNT(pid) FROM casts;
SELECT COUNT(mid) FROM movie_directors;
SELECT COUNT(id) FROM actor;
UPDATE movie SET name = 'La nostra guerra' WHERE name = 'La nostra guerra';
UPDATE movie_directors SET mid = '392253' WHERE mid = '392253';
UPDATE movie_directors SET did = '67706' WHERE did = '67706';
SELECT COUNT(lname) FROM actor;
SELECT COUNT(pid) FROM casts;
SELECT COUNT(fname) FROM actor;
SELECT COUNT(pid) FROM casts;
UPDATE directors SET fname = ' Rodger' WHERE fname = ' Rodger';
